# Generated by Django 4.2 on 2023-04-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='Mobile',
            field=models.CharField(max_length=20),
        ),
    ]
